server:
  port: 9527
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

  instance:
    prefer-ip-address: true
zuul:
  #ignored-services: microservice-dept  #新添加内容
  routes:
    mydept.serviceId: microservice-dept
    mydept.path: /mydept/**
  prefix: /hand
